-- 1. Find the titles of movies except starting with a that have been rented more than 30 times, and sort them in desc order.
select title, COUNT(rental.rental_id) as rental_count
from film
join inventory on inventory.film_id = film.film_id
join rental on rental.inventory_id = inventory.inventory_id
where title not like 'A%'
group by title
having rental_count > 30
order by rental_count desc;

-- 2. Find the total revenue generated by store1.

select store_id, sum(amount) as revenue from customer
join payment on customer.customer_id = payment.customer_id
where store_id = 1
group by store_id;


-- 3. Find the titles of movies in the 'horror' category and sort them based on the last character of the title

select title from film
join film_category on film.film_id = film_category.film_id
join category on category.category_id = film_category.category_id
where name = 'Horror'
ORDER BY RIGHT(film.title, 1);


-- 4. Retrieve the top 5 customers whose name starts with E and have made the highest number of rentals. Display their customer IDs and the total number of rentals they have made.

select customer.customer_id, first_name, sum(amount) as total_rental, count(rental_id) as times_rented from customer
join payment on payment.customer_id = customer.customer_id
where first_name like 'E%'
GROUP by customer.customer_id
Order by times_rented desc
limit 5;

-- 5. Find the total number of films available in each category, and list the categories in descending order of film count.

select category.name, category.category_id, count(film_category.film_id) as film_count from film
join film_category on film.film_id = film_category.film_id
join category on category.category_id = film_category.category_id
GROUP by category.category_id
order by 3 desc;